t69114: fix blocking behaviour on streamed gets, specify chunk_size
When getting a large file have the status check on the Response
object from the get (prior to iterating over the chunks) wound
up blocking.

Instead, perform the check after the streaming. Note that
the "response.text" will already be consumed at this point,
so we need to handle that exception in
canfar.common.client.Client.check_status().

DataClient constructor now takes chunk_size as option.

diff --git a/cadc-clients/test/inttest b/cadc-clients/test/inttest
--- a/cadc-clients/test/inttest
+++ b/cadc-clients/test/inttest
@@ -70,6 +70,13 @@ newmd5=`md5sum $TESTFILE`
 [[ "$newmd5" != "$MD5" ]] && echo " md5 [FAIL]" && exit -1
 echo " [OK]"
 
+echo -n "get file from archive with different chunk_size..."
+$COPYCMD get $ARCHIVE $TESTFILE --chunk_size=4096
+[[ "$?" != "0" ]] && echo " cmd [FAIL]" && exit -1
+newmd5=`md5sum $TESTFILE`
+[[ "$newmd5" != "$MD5" ]] && echo " md5 [FAIL]" && exit -1
+echo " [OK]"
+
 echo -n "anonymous get file from archive..."
 $COPYCMD get $ARCHIVE $TESTFILE --anonymous
 [[ "$?" != "0" ]] && echo " cmd [FAIL]" && exit -1
